# Jekyll configuration for GitHub Pages
title: "FlightStream"
description: "High-performance Apache Arrow Flight streaming framework with plugin architecture for Node.js"
url: "https://ggauravr.github.io"
baseurl: "/flightstream"

# Repository information
repository: "ggauravr/flightstream"
github_username: "ggauravr"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - getting-started.md
  - tutorial.md
  - api-reference.md
  - examples.md
  - contributing.md

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_guides"
    values:
      layout: "guide"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 